apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-check-indexing-complete
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: check-complete
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XPUT http://hmpps-prisoner-search-indexer/maintain-index/check-complete
          restartPolicy: Never
