---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-restore-script
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
{{ .Files.Get "restore.sh" | indent 4 }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-opensearch-restore
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "30 */4 * * *"
  suspend: {{ .Values.cron.suspend_restore }}
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      backoffLimit: 0
      activeDeadlineSeconds: 2400
      template:
        spec:
          containers:
          - name: opensearch-restore
            image: "ghcr.io/ministryofjustice/hmpps-devops-tools:latest"
            command:
            - /bin/entrypoint.sh
            volumeMounts:
            - name: opensearch-restore-script 
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            env:
            - name: OPENSEARCH_PROXY_URL
              valueFrom:
                secretKeyRef:
                  name: opensearch
                  key: url
            - name: SNAPSHOT_ROLE_ARN
              valueFrom:
                secretKeyRef:
                  name: os-snapshot-role
                  key: snapshot_role_arn
            - name: BUCKET_NAME
              valueFrom: 
                secretKeyRef:
                  name: os-snapshot-bucket
                  key: bucket_name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NAMESPACE_OVERRIDE
              value: {{ .Values.cron.snapshot_namespace }}
            - name: PRISON_API_BASE_URL
              value: {{ index .Values "generic-service" "env" "API_BASE_URL_PRISON_API" }}
            securityContext:
              capabilities:
                drop:
                - ALL
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
          restartPolicy: "Never"
          volumes:
          - name: opensearch-restore-script
            configMap:
              name: opensearch-restore-script
              defaultMode: 0755
            securityContext:
              capabilities:
                drop:
                - ALL
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
