generic-service:
  nameOverride: hmpps-prisoner-search
  productId: DPS072

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-prisoner-search
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-prisoner-search-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-prisoner-search:
      PRISON_API_CLIENT_ID: "PRISON_API_CLIENT_ID"
      PRISON_API_CLIENT_SECRET: "PRISON_API_CLIENT_SECRET"
    opensearch:
      OPENSEARCH_URIS: "url"

  allowlist:
    analyticplatform-1: 34.250.17.221/32
    analyticplatform-2: 34.251.212.33/32
    analyticplatform-3: 34.252.4.39/32
    hmp-fosseway-1: 35.177.153.88/32
    hmp-fosseway-2: 52.56.95.43/32
    hmp-fosseway-3: 52.56.57.70/32
    hmp-fosseway-4: 18.135.112.100/32
    hmp-fosseway-5: 18.135.112.128/32
    hmp-fosseway-6: 18.135.112.181/32
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-prisoner-search
  alertSeverity: syscon
