---
generic-service:
  nameOverride: hmpps-prisoner-search

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-prisoner-search
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-prisoner-search-cert
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /synthetic-monitor {
          deny all;
          return 401;
        }
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    hmpps-prisoner-search:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"

    opensearch:
      OPENSEARCH_URIS: "url"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live-1: "35.178.209.113/32"
    cloudplatform-live-2: "3.8.51.207/32"
    cloudplatform-live-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: hmpps-prisoner-search
  alertSeverity: syscon
