server:
  shutdown: immediate

aws:
  provider: localstack

api:
  base:
    url:
      oauth: http://localhost:8090/auth
      prison-api: http://localhost:8093
      restricted-patients: http://localhost:8095
      incentives: http://localhost:8096

prison-api:
  client:
    id: prisoner-offender-search-client
    secret: clientsecret

restricted-patients:
  client:
    id: prisoner-search-to-restricted-patients-api
    secret: clientsecret

incentives:
  client:
    id: incentives-api
    secret: clientsecret

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

opensearch:
  uris: http://localhost:4566
  pathPrefix: /opensearch/eu-west-2/os01

index-build:
  page-size: 1000
  complete-threshold: 50

hmpps.sqs:
  provider: localstack
  queues:
    index:
      queueName: index-queue
      dlqName: index-dlq
  topics:
    hmppseventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps-event-topic
