server:
  shutdown: immediate

aws:
  provider: localstack

api:
  base:
    url:
      oauth: http://localhost:8090/auth
      prison-api: http://localhost:8093
      restricted-patients: http://localhost:8095
      incentives: http://localhost:8096

prison-api:
  client:
    id: prisoner-offender-search-client
    secret: clientsecret

restricted-patients:
  client:
    id: prisoner-search-to-restricted-patients-api
    secret: clientsecret

incentives:
  client:
    id: incentives-api
    secret: clientsecret

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

opensearch:
  uris: http://os01.eu-west-2.opensearch.localhost.localstack.cloud:4566
