version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@7

parameters:
  releases-slack-channel:
    type: string
    default: dps-releases
  build-model:
    type: boolean
    default: false
  build-indexer:
    type: boolean
    default: false
  build-search:
    type: boolean
    default: false

jobs:
  validate-model:
    executor:
      name: hmpps/java
      tag: "19.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "model/build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew :model:check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "model/build.gradle.kts" }}
      - store_test_results:
          path: model/build/test-results
      - store_artifacts:
          path: model/build/reports/tests

  validate:
    parameters:
      project:
        type: string
    executor:
      name: hmpps/localstack
      jdk_tag: "19.0"
      localstack_tag: "2.0"
      localstack_type: "localstack"
      services: "opensearch,sns,sqs"
    steps:
      - checkout
      - hmpps/install_aws_cli
      - hmpps/wait_till_ready
      - run:
          name: Set up opensearch domain
          command: localstack/setup-opensearch.sh
      - hmpps/wait_till_ready:
          port: 4566
          host: os01.eu-west-2.opensearch.localhost.localstack.cloud
      - restore_cache:
          keys:
            - gradle-{{ checksum "<< parameters.project >>/build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew :<< parameters.project >>:check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "<< parameters.project >>/build.gradle.kts" }}
      - store_test_results:
          path: << parameters.project >>/build/test-results
      - store_artifacts:
          path: << parameters.project >>/build/reports/tests

  no-op:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run: echo "no-op"

workflows:
  version: 2
  no-changes:
    when:
      not:
        or:
          - << pipeline.parameters.build-model >>
          - << pipeline.parameters.build-indexer >>
          - << pipeline.parameters.build-search >>
    jobs:
      - no-op
  build-test-model:
    when: << pipeline.parameters.build-model >>
    jobs:
      - validate-model:
          filters:
            tags:
              ignore: /.*/
  build-test-and-deploy-indexer:
    when: << pipeline.parameters.build-indexer >>
    jobs:
      - validate:
          name: validate-indexer
          project: hmpps-prisoner-search-indexer
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint-indexer
          helm_dir: hmpps-prisoner-search-indexer/helm_deploy
          chart_name: hmpps-prisoner-search-indexer

      - hmpps/build_multiplatform_docker:
          name: build_docker-indexer
          image_name: quay.io/hmpps/hmpps-prisoner-search-indexer
          additional_docker_build_args: -f hmpps-prisoner-search-indexer/Dockerfile
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev-indexer
          env: "dev"
          jira_update: true
          context:
            - hmpps-common-vars
            - hmpps-prisoner-search
          k8s_deployment_name: hmpps-prisoner-search-indexer
          chart_name: hmpps-prisoner-search-indexer
          release_name: hmpps-prisoner-search-indexer
          helm_dir: hmpps-prisoner-search-indexer/helm_deploy
          filters:
            branches:
              only:
                - main
          requires:
            - validate-indexer
            - build_docker-indexer
            - helm_lint-indexer
          helm_timeout: 5m
  build-test-and-deploy-search:
    when: << pipeline.parameters.build-search >>
    jobs:
      - validate:
          name: validate-search
          project: hmpps-prisoner-search
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint-search
          helm_dir: hmpps-prisoner-search/helm_deploy

      - hmpps/build_multiplatform_docker:
          name: build_docker-search
          additional_docker_build_args: -f hmpps-prisoner-search/Dockerfile
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev-search
          env: "dev"
          jira_update: true
          context:
            - hmpps-common-vars
            - hmpps-prisoner-search
          helm_dir: hmpps-prisoner-search/helm_deploy
          filters:
            branches:
              only:
                - main
          requires:
            - validate-search
            - build_docker-search
            - helm_lint-search
          helm_timeout: 5m
