version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@8

parameters:
  releases-slack-channel:
    type: string
    default: dps-releases
  build-common:
    type: boolean
    default: false
  build-indexer:
    type: boolean
    default: false
  build-search:
    type: boolean
    default: false

jobs:
  validate-common:
    executor:
      name: hmpps/java
      tag: "21.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "common/build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew :common:check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "common/build.gradle.kts" }}
      - store_test_results:
          path: common/build/test-results
      - store_artifacts:
          path: common/build/reports/tests

  validate-search:
    parameters:
      project:
        type: string
    executor:
      name: hmpps/localstack
      jdk_tag: "21.0"
      localstack_tag: "2.3"
      localstack_type: "localstack"
      services: "opensearch,sns,sqs"
    steps:
      - checkout
      - hmpps/install_aws_cli
      - hmpps/wait_till_ready
      - run:
          name: Set up opensearch domain
          command: localstack/setup-opensearch.sh
      - hmpps/wait_till_ready:
          port: 4566
          host: os01.eu-west-2.opensearch.localhost.localstack.cloud
      - restore_cache:
          keys:
            - gradle-{{ checksum "<< parameters.project >>/build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew :<< parameters.project >>:check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "<< parameters.project >>/build.gradle.kts" }}
      - store_test_results:
          path: << parameters.project >>/build/test-results
      - store_artifacts:
          path: << parameters.project >>/build/reports/tests

  validate-indexer:
    parameters:
      project:
        type: string
    executor:
      name: hmpps/java_localstack_postgres
      jdk_tag: "21.0"
      localstack_tag: "2.3"
      localstack_type: "localstack"
      services: "opensearch,sns,sqs"
      postgres_tag: "15"
      postgres_username: "pos"
      postgres_password: "pos"
    steps:
      - checkout
      - hmpps/install_aws_cli
      - hmpps/wait_till_ready
      - run:
          name: Set up opensearch domain
          command: localstack/setup-opensearch.sh
      - hmpps/wait_till_ready:
          port: 4566
          host: os01.eu-west-2.opensearch.localhost.localstack.cloud
      - hmpps/wait_till_ready_postgres
      - restore_cache:
          keys:
            - gradle-{{ checksum "<< parameters.project >>/build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew :<< parameters.project >>:check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "<< parameters.project >>/build.gradle.kts" }}
      - store_test_results:
          path: << parameters.project >>/build/test-results
      - store_artifacts:
          path: << parameters.project >>/build/reports/tests
  no-op:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run: echo "no-op"

workflows:
  version: 2
  no-changes:
    when:
      not:
        or:
          - << pipeline.parameters.build-common >>
          - << pipeline.parameters.build-indexer >>
          - << pipeline.parameters.build-search >>
    jobs:
      - no-op
  build-test-common:
    when: << pipeline.parameters.build-common >>
    jobs:
      - validate-common:
          filters:
            tags:
              ignore: /.*/
  build-test-and-deploy-indexer:
    when: << pipeline.parameters.build-indexer >>
    jobs:
      - validate-indexer:
          name: validate-indexer
          project: hmpps-prisoner-search-indexer
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint-indexer
          helm_dir: hmpps-prisoner-search-indexer/helm_deploy
          chart_name: hmpps-prisoner-search-indexer
      - hmpps/build_multiplatform_docker:
          name: build_docker-indexer
          image_name: quay.io/hmpps/hmpps-prisoner-search-indexer
          additional_docker_build_args: -f hmpps-prisoner-search-indexer/Dockerfile
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev-indexer
          env: "dev"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context:
            - hmpps-common-vars
          k8s_deployment_name: hmpps-prisoner-search-indexer
          chart_name: hmpps-prisoner-search-indexer
          release_name: hmpps-prisoner-search-indexer
          helm_dir: hmpps-prisoner-search-indexer/helm_deploy
          filters:
            branches:
              only:
                - main
          requires:
            - validate-indexer
            - build_docker-indexer
            - helm_lint-indexer
          helm_timeout: 5m
      - hmpps/smoke_test:
          name: smoke_test-indexer
          command: "./gradlew :hmpps-prisoner-search-indexer:testSmoke -Dtestlogger.showStandardStreams=true"
          context: hmpps-smoketest-common-vars
          jdk_tag: "21.0"
          requires:
            - deploy_dev-indexer
      - hmpps/deploy_env:
          name: deploy_preprod-indexer
          env: "preprod"
          jira_update: true
          jira_env_type: staging
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context:
            - hmpps-common-vars
            - hmpps-prisoner-search-preprod
          k8s_deployment_name: hmpps-prisoner-search-indexer
          chart_name: hmpps-prisoner-search-indexer
          release_name: hmpps-prisoner-search-indexer
          helm_dir: hmpps-prisoner-search-indexer/helm_deploy
          requires:
            - smoke_test-indexer
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod-indexer
      - hmpps/deploy_env:
          name: deploy_prod-indexer
          env: "prod"
          jira_update: true
          jira_env_type: production
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          slack_notification: true
          context:
            - hmpps-common-vars
            - hmpps-prisoner-search-prod
          k8s_deployment_name: hmpps-prisoner-search-indexer
          chart_name: hmpps-prisoner-search-indexer
          release_name: hmpps-prisoner-search-indexer
          helm_dir: hmpps-prisoner-search-indexer/helm_deploy
          requires:
            - request-prod-approval
  build-test-and-deploy-search:
    when: << pipeline.parameters.build-search >>
    jobs:
      - validate-search:
          name: validate-search
          project: hmpps-prisoner-search
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint-search
          helm_dir: hmpps-prisoner-search/helm_deploy

      - hmpps/build_multiplatform_docker:
          name: build_docker-search
          additional_docker_build_args: -f hmpps-prisoner-search/Dockerfile
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev-search
          env: "dev"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context:
            - hmpps-common-vars
          helm_dir: hmpps-prisoner-search/helm_deploy
          filters:
            branches:
              only:
                - main
          requires:
            - validate-search
            - build_docker-search
            - helm_lint-search
          helm_timeout: 5m
      - hmpps/smoke_test:
          name: smoke_test-search
          command: "./gradlew :hmpps-prisoner-search:testSmoke -Dtestlogger.showStandardStreams=true"
          context: hmpps-smoketest-common-vars
          jdk_tag: "21.0"
          requires:
            - deploy_dev-search
      - hmpps/deploy_env:
          name: deploy_preprod-search
          env: "preprod"
          jira_update: true
          jira_env_type: staging
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context:
            - hmpps-common-vars
            - hmpps-prisoner-search-preprod
          helm_dir: hmpps-prisoner-search/helm_deploy
          requires:
            - smoke_test-search
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod-search
      - hmpps/deploy_env:
          name: deploy_prod-search
          env: "prod"
          jira_update: true
          jira_env_type: production
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          slack_notification: true
          context:
            - hmpps-common-vars
            - hmpps-prisoner-search-prod
          helm_dir: hmpps-prisoner-search/helm_deploy
          requires:
            - request-prod-approval
