version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@7

parameters:
  releases-slack-channel:
    type: string
    default: dps-releases
  build-model:
    type: boolean
    default: false
  build-indexer:
    type: boolean
    default: false
  build-search:
    type: boolean
    default: false

jobs:
  validate-model:
    executor:
      name: hmpps/java
      tag: "19.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "model/build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew :model:check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "model/build.gradle.kts" }}
      - store_test_results:
          path: model/build/test-results
      - store_artifacts:
          path: model/build/reports/tests

  validate-indexer:
    executor:
      name: hmpps/localstack
      jdk_tag: "19.0"
      localstack_tag: "2.0"
      localstack_type: "localstack"
      services: "opensearch,sns,sqs"
    steps:
      - checkout
      - hmpps/install_aws_cli
      - hmpps/wait_till_ready
      - run:
          name: Set up opensearch domain
          command: localstack/setup-opensearch.sh
      - hmpps/wait_till_ready:
          port: 4566
          host: os01.eu-west-2.opensearch.localhost.localstack.cloud
      - restore_cache:
          keys:
            - gradle-{{ checksum "hmpps-prisoner-search-indexer/build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew :hmpps-prisoner-search-indexer:check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "hmpps-prisoner-search-indexer/build.gradle.kts" }}
      - store_test_results:
          path: hmpps-prisoner-search-indexer/build/test-results
      - store_artifacts:
          path: hmpps-prisoner-search-indexer/build/reports/tests

workflows:
  version: 2
  build-test-and-deploy-model:
    when: << pipeline.parameters.build-model >>
    jobs:
      - validate-model:
          filters:
            tags:
              ignore: /.*/
  build-test-and-deploy-indexer:
    when: << pipeline.parameters.build-indexer >>
    jobs:
      - validate-indexer:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint-indexer
          helm_dir: hmpps-prisoner-search-indexer/helm_deploy

#      - hmpps/build_multiplatform_docker:
#          name: build_docker
#          filters:
#            branches:
#              only:
#                - main
#      - hmpps/deploy_env:
#          name: deploy_dev
#          env: "dev"
#          jira_update: true
#          context: hmpps-common-vars
#          filters:
#            branches:
#              only:
#                - main
#          requires:
#            - validate
##            - build_docker
##            - helm_lint
#          helm_timeout: 5m
#      - request-preprod-approval:
#          type: approval
#          requires:
#            - deploy_dev
#      - hmpps/deploy_env:
#          name: deploy_preprod
#          env: "preprod"
#          jira_update: true
#          jira_env_type: staging
#          context:
#            - hmpps-common-vars
#            - hmpps-prisoner-search-indexer-preprod
#          requires:
#            - request-preprod-approval
#          helm_timeout: 5m
#      - request-prod-approval:
#          type: approval
#          requires:
#            - deploy_preprod
#      - hmpps/deploy_env:
#          name: deploy_prod
#          env: "prod"
#          jira_update: true
#          jira_env_type: production
#          slack_notification: true
#          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
#          context:
#            - hmpps-common-vars
#            - hmpps-prisoner-search-indexer-prod
#          requires:
#            - request-prod-approval
#          helm_timeout: 5m

