---
generic-service:
  ingress:
    host: prisoner-search-indexer.prison.service.justice.gov.uk

  env:
    API_BASE_URL_OAUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_PRISON_API: "https://api.prison.service.justice.gov.uk"
    API_BASE_URL_RESTRICTED_PATIENTS: "https://restricted-patients-api.hmpps.service.justice.gov.uk"
    API_BASE_URL_INCENTIVES: "https://incentives-api.hmpps.service.justice.gov.uk"
    DIFF_HOST: "https://prisoner-search.prison.service.justice.gov.uk"

  rdsAlertsDatabases:
    cloud-platform-beab851ca55f05a8: "prisoner search indexer"
