---
generic-service:
  ingress:
    host: prisoner-search-indexer.prison.service.justice.gov.uk

  env:
    API_BASE_URL_OAUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_PRISON_API: "https://api.prison.service.justice.gov.uk"
    API_BASE_URL_RESTRICTED_PATIENTS: "https://restricted-patients-api.hmpps.service.justice.gov.uk"
    API_BASE_URL_INCENTIVES: "https://incentives-api.hmpps.service.justice.gov.uk"
    DIFF_HOST: "https://prisoner-search.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  rdsAlertsDatabases:
    cloud-platform-beab851ca55f05a8: "prisoner search indexer"
  sqsAlertsQueueNames:
    - "syscon-devs-prod-hmpps_prisoner_search_domain_dlq"
    - "syscon-devs-prod-hmpps_prisoner_search_domain_queue"
    - "syscon-devs-prod-hmpps_prisoner_search_offender_dlq"
    - "syscon-devs-prod-hmpps_prisoner_search_offender_queue"
  sqsAlertsOldestThreshold: 10
  sqsAlertsTotalMessagesThreshold: 2

indexQueueNames:
  - "syscon-devs-prod-hmpps_prisoner_search_index_queue_dl"
  - "syscon-devs-prod-hmpps_prisoner_search_index_queue"
