---
generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-search-preprod.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"

generic-prometheus-alerts:
  businessHoursOnly: true
