generic-service:
  ingress:
    host: prisoner-search.prison.service.justice.gov.uk

  # Additional allowlist rules
  # See also allowlist values helm_deploy/hmpps-prisoner-search/values.yaml
  allowlist:
    groups:
      - internal
      - prum-prod

  env:
    API_BASE_URL_HMPPS_AUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_PRISON_API: "https://prison-api.prison.service.justice.gov.uk"
    SEARCH_REGIME: RED
