generic-service:
  ingress:
    host: prisoner-search.prison.service.justice.gov.uk

  # Additional allowlist rules
  # See also allowlist values helm_deploy/prisoner-offender-search/values.yaml
  allowlist:
    prum-prod-platform-1: 18.170.20.75/32
    prum-prod-platform-2: 35.177.223.199/32
    prum-prod-platform-3: 18.170.155.82/32

  env:
    HMPPS_AUTH_BASE_URI: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PRISON_API_BASE_URI: "https://api.prison.service.justice.gov.uk"
