generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-search-preprod.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_HMPPS_AUTH: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_PRISON_API: "https://prison-api-preprod.prison.service.justice.gov.uk"

  # Additional allowlist rules
  # See also allowlist values helm_deploy/hmpps-prisoner-search/values.yaml
  allowlist:
    groups:
      - internal
      - prum-test

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
