server:
  shutdown: immediate


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pos
    username: pos
    password: pos

aws:
  provider: localstack

api:
  base:
    url:
      oauth: http://localhost:8090/auth
      prison-api: http://localhost:8093
      restricted-patients: http://localhost:8095
      incentives: http://localhost:8096
#      oauth: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
#      prison-api: https://prison-api-dev.prison.service.justice.gov.uk
#      restricted-patients: https://restricted-patients-api-dev.hmpps.service.justice.gov.uk
#      incentives: https://incentives-api-dev.hmpps.service.justice.gov.uk

prison-api:
  client:
    id: prisoner-offender-search-client
    secret: clientsecret

restricted-patients:
  client:
    id: prisoner-search-to-restricted-patients-api
    secret: clientsecret

incentives:
  client:
    id: incentives-api
    secret: clientsecret

opensearch:
  uris: http://os01.eu-west-2.opensearch.localhost.localstack.cloud:4566

index-build:
  page-size: 1000

hmpps.sqs:
  provider: localstack
  queues:
    index:
      queueName: index-queue
      dlqName: index-dlq
    hmppsdomainqueue:
      queueName: hmpps-domain-queue
      dlqName: hmpps-domain-dlq
    offenderqueue:
      queueName: offender-queue
      dlqName: offender-dlq
    publish:
      queueName: publish-queue
      dlqName: publish-dlq
  topics:
    hmppseventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps-event-topic
