generic-service:
  nameOverride: hmpps-prisoner-search-indexer
  productId: DPS072

  serviceAccountName: hmpps-prisoner-search-indexer

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-prisoner-search-indexer
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-prisoner-search-indexer-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
        location /maintain-index/check-complete {
          deny all;
          return 401;
        }
        location /compare-index/size {
          deny all;
          return 401;
        }
        location /prisoner-differences/delete {
          deny all;
          return 401;
        }
        location /refresh-index/automated {
          deny all;
          return 401;
        }
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: "true"

  namespace_secrets:
    hmpps-prisoner-search-indexer:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      RESTRICTED_PATIENTS_CLIENT_ID: "RESTRICTED_PATIENTS_CLIENT_ID"
      RESTRICTED_PATIENTS_CLIENT_SECRET: "RESTRICTED_PATIENTS_CLIENT_SECRET"
      PRISON_API_CLIENT_ID: "PRISON_API_CLIENT_ID"
      PRISON_API_CLIENT_SECRET: "PRISON_API_CLIENT_SECRET"
      INCENTIVES_CLIENT_ID: "INCENTIVES_CLIENT_ID"
      INCENTIVES_CLIENT_SECRET: "INCENTIVES_CLIENT_SECRET"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSEVENTTOPIC_ARN: "topic_arn"
    prisoner-search-indexer-dlq:
      HMPPS_SQS_QUEUES_INDEX_DLQ_NAME: "sqs_queue_name"
    prisoner-search-indexer-queue:
      HMPPS_SQS_QUEUES_INDEX_QUEUE_NAME: "sqs_queue_name"
    sqs-domain-event-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-domain-event-dlq-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINQUEUE_DLQ_NAME: "sqs_queue_name"
    sqs-offender-event-secret:
      HMPPS_SQS_QUEUES_OFFENDERQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-offender-event-dlq-secret:
      HMPPS_SQS_QUEUES_OFFENDERQUEUE_DLQ_NAME: "sqs_queue_name"
    prisoner-search-publish-dlq:
      HMPPS_SQS_QUEUES_PUBLISH_DLQ_NAME: "sqs_queue_name"
    prisoner-search-publish-queue:
      HMPPS_SQS_QUEUES_PUBLISH_QUEUE_NAME: "sqs_queue_name"
    rds-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"

    opensearch:
      OPENSEARCH_URIS: "url"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-prisoner-search-indexer
  alertSeverity: syscon
  sqsAlertsTotalMessagesThreshold: 0

cron:
  retry_dlqs_schedule: "*/10 * * * *"
  index_size_schedule: "*/10 * * * *"
  check_index_schedule: "*/15 * * * *"
  index_refresh_schedule: "05 21 * * 1,3,5"
  remove_differences_schedule: "45 22 * * *"
  snapshot_schedule: "42 1 * * *"

  # default is to suspend the restore - only want it happening on preprod
  suspend_restore: true

# had to copy these from https://github.com/ministryofjustice/hmpps-helm-charts/blob/main/charts/generic-prometheus-alerts/values.yaml
# as want to override the default values for only some of our queues
runbookUrl: https://github.com/ministryofjustice/hmpps-helm-charts/blob/main/charts/generic-prometheus-alerts/RUNBOOK.md#
grafanaUrl: https://grafana.live.cloud-platform.service.justice.gov.uk
