generic-service:
  nameOverride: hmpps-prisoner-search-indexer
  productId: DPS072

  serviceAccountName: hmpps-prisoner-search-indexer

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-prisoner-search-indexer
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-prisoner-search-indexer-cert
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine On
      # team here grants access to the OpenSearch logs to delve into the cause of the blockage
      SecDefaultAction "phase:2,pass,log,tag:github_team=syscon-devs,tag:namespace={{ .Release.Namespace }}"
      # Default is only GET HEAD POST OPTIONS so need to include PUT etc.
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE,setvar:tx.paranoia_level=3"
      # Block Detectify scanner with 418
      SecRule REQUEST_HEADERS:User-Agent "@pm detectify Detectify DETECTIFY" "id:800003,phase:1,deny,status:418,log,tag:github_team=syscon-devs,tag:namespace={{ .Release.Namespace }}"
      # Change default denial to be a 406 so that we can tell easily that it is modsecurity doing the blocking
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"

  env:
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: "true"

  namespace_secrets:
    hmpps-prisoner-search-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-prisoner-search-indexer-client-creds:
      ALERTS_CLIENT_ID: "ALERTS_CLIENT_ID"
      ALERTS_CLIENT_SECRET: "ALERTS_CLIENT_SECRET"
      COMPLEXITY_OF_NEED_CLIENT_ID: "COMPLEXITY_OF_NEED_CLIENT_ID"
      COMPLEXITY_OF_NEED_CLIENT_SECRET: "COMPLEXITY_OF_NEED_CLIENT_SECRET"
      INCENTIVES_CLIENT_ID: "INCENTIVES_CLIENT_ID"
      INCENTIVES_CLIENT_SECRET: "INCENTIVES_CLIENT_SECRET"
      NOMIS_API_CLIENT_ID: "NOMIS_API_CLIENT_ID"
      NOMIS_API_CLIENT_SECRET: "NOMIS_API_CLIENT_SECRET"
      PRISON_API_CLIENT_ID: "PRISON_API_CLIENT_ID"
      PRISON_API_CLIENT_SECRET: "PRISON_API_CLIENT_SECRET"
      RESTRICTED_PATIENTS_CLIENT_ID: "RESTRICTED_PATIENTS_CLIENT_ID"
      RESTRICTED_PATIENTS_CLIENT_SECRET: "RESTRICTED_PATIENTS_CLIENT_SECRET"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSEVENTTOPIC_ARN: "topic_arn"
    prisoner-search-indexer-dlq:
      HMPPS_SQS_QUEUES_INDEX_DLQ_NAME: "sqs_queue_name"
    prisoner-search-indexer-queue:
      HMPPS_SQS_QUEUES_INDEX_QUEUE_NAME: "sqs_queue_name"
    sqs-domain-event-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-domain-event-dlq-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINQUEUE_DLQ_NAME: "sqs_queue_name"
    sqs-offender-event-secret:
      HMPPS_SQS_QUEUES_OFFENDERQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-offender-event-dlq-secret:
      HMPPS_SQS_QUEUES_OFFENDERQUEUE_DLQ_NAME: "sqs_queue_name"
    prisoner-search-publish-dlq:
      HMPPS_SQS_QUEUES_PUBLISH_DLQ_NAME: "sqs_queue_name"
    prisoner-search-publish-queue:
      HMPPS_SQS_QUEUES_PUBLISH_QUEUE_NAME: "sqs_queue_name"
    rds-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"

    opensearch:
      OPENSEARCH_URIS: "url"

  allowlist:
    groups:
      - internal

  # The name has max length of 22 chars (Cronjob name max length is 52 chars, including prefix "hmpps-prisoner-search-indexer-")
  # The type must exist in enum BatchType
  batchjobs:
    - name: compare-index-size
      type: COMPARE_INDEX_SIZE
      schedule: "*/10 * * * *"
    # Start earlier than the active refresh as this must end before midnight otherwise there will be alert mismatches (see SDIT-2995):
    - name: full-index-refresh
      type: FULL_INDEX_REFRESH
      schedule: "0 20 * * MON,THU"
    - name: active-index-refresh
      type: ACTIVE_INDEX_REFRESH
      schedule: "05 21 * * SUN,TUE,WED,FRI,SAT"

generic-prometheus-alerts:
  targetApplication: hmpps-prisoner-search-indexer
  alertSeverity: syscon
  sqsAlertsTotalMessagesThreshold: "0"

cron:
  snapshot_schedule: "42 1 * * *"

  # default is to suspend the restore - only want it happening on preprod
  suspend_restore: true

# had to copy these from https://github.com/ministryofjustice/hmpps-helm-charts/blob/main/charts/generic-prometheus-alerts/values.yaml
# as want to override the default values for only some of our queues
runbookUrl: https://github.com/ministryofjustice/hmpps-helm-charts/blob/main/charts/generic-prometheus-alerts/RUNBOOK.md#
grafanaUrl: https://grafana.live.cloud-platform.service.justice.gov.uk
