---
generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-search-indexer-dev.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

generic-prometheus-alerts:
  rdsAlertsDatabases:
    cloud-platform-99ebbe3b76dc9264: "prisoner search indexer"
