---
generic-service:
  ingress:
    host: hmpps-prisoner-search-indexer.hmpps.service.justice.gov.uk

  env:
    API_BASE_URL_OAUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_PRISON_API: "https://api.prison.service.justice.gov.uk"
    API_BASE_URL_RESTRICTED_PATIENTS: "https://restricted-patients-api.hmpps.service.justice.gov.uk"
    API_BASE_URL_INCENTIVES: "https://incentives-api.hmpps.service.justice.gov.uk"
