---
generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-prisoner-search-indexer-preprod.hmpps.service.justice.gov.uk

  serviceAccountName: hmpps-prisoner-search-indexer-preprod

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_PRISON_API: "https://api-preprod.prison.service.justice.gov.uk"
    API_BASE_URL_RESTRICTED_PATIENTS: "https://restricted-patients-api-preprod.hmpps.service.justice.gov.uk"
    API_BASE_URL_INCENTIVES: "https://incentives-api-preprod.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  businessHoursOnly: true
