name: Build & push docker image and deploy to environment

on:
  workflow_call:
    inputs:
      docker_registry:
        description: Docker registry
        required: true
        type: string
      registry_org:
        description: Docker registry organisation
        required: true
        type: string
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable tags
        required: false
        type: string
      tag_latest:
        description: Tag docker image as 'latest'
        required: false
        type: boolean
        default: true
      upload_image_artifact:
        description: Upload image to artifacts in GitHub Actions
        required: false
        type: boolean
        default: false
      image_artifact_retention_days:
        description: Number of days to keep the image in artifacts
        required: false
        type: number
        default: 7
      additional_docker_build_args:
        description: Additional docker build arguments
        required: false
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        type: boolean
      load:
        description: Load docker image into local docker
        required: false
        type: boolean
        default: false
      docker_multiplatform:
        description: Docker image build multiplatform or not
        required: true
        type: boolean
        default: true
      image_name:
        description: Name of the image
        required: false
        type: string
    secrets:
      HMPPS_QUAYIO_USER:
        required: false
      HMPPS_QUAYIO_TOKEN:
        required: false

    outputs:
      app_version:
        description: The version of the app as generated by create_app_version
        value: ${{ jobs.docker_build.outputs.version }}

permissions:
  contents: read
  packages: write

jobs:
  docker_build:
    name: Build docker image
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.app_version.outputs.version }}
    steps:
      - id: app_version
        name: Application version creators
        uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/create_app_version@v2 # WORKFLOW_VERSION
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_docker.yml # LOCAL VERSION
        if: ${{ ( inputs.docker_registry  == 'ghcr.io' ) && ( ! inputs.docker_multiplatform )}}
        with:
          image_name: ${{ inputs.image_name || github.event.repository.name }}
          docker_registry: ${{ inputs.docker_registry }}
          registry_org: ${{ inputs.registry_org }}
          additional_docker_tag: ${{ inputs.additional_docker_tag }}
          tag_latest: ${{ inputs.tag_latest }}
          upload_image_artifact: ${{ inputs.upload_image_artifact }}
          image_artifact_retention_days: ${{ inputs.image_artifact_retention_days }}
          push: ${{ inputs.push }}
          load: ${{ inputs.load }}
          app_version: ${{ steps.app_version.outputs.version }}
          additional_docker_build_args: ${{ inputs.additional_docker_build_args }}

      - uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/build_docker@v2 # WORKFLOW_VERSION
        if: ${{ ( inputs.docker_registry  == 'quay.io' ) && ( ! inputs.docker_multiplatform )}}
        with:
          repository_name: ${{ github.event.repository.name }}
          docker_registry: ${{ inputs.docker_registry }}
          registry_org: ${{ inputs.registry_org }}
          additional_docker_tag: ${{ inputs.additional_docker_tag }}
          tag_latest: ${{ inputs.tag_latest }}
          upload_image_artifact: ${{ inputs.upload_image_artifact }}
          image_artifact_retention_days: ${{ inputs.image_artifact_retention_days }}
          push: ${{ inputs.push }}
          load: ${{ inputs.load }}
          app_version: ${{ steps.app_version.outputs.version }}
          HMPPS_QUAYIO_USER: ${{ secrets.HMPPS_QUAYIO_USER }}
          HMPPS_QUAYIO_TOKEN: ${{ secrets.HMPPS_QUAYIO_TOKEN}}
          additional_docker_build_args: ${{ inputs.additional_docker_build_args }}
          # git_head_ref: ${{ github.head_ref }}
          # git_branch_ref: ${{ github.ref_name }}

      - uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/build_multiplatform_docker@v2 # WORKFLOW_VERSION
        if: ${{ ( inputs.docker_registry  == 'ghcr.io' ) && ( inputs.docker_multiplatform )}}
        with:
          repository_name: ${{ github.event.repository.name }}
          docker_registry: ${{ inputs.docker_registry }}
          registry_org: ${{ inputs.registry_org }}
          additional_docker_tag: ${{ inputs.additional_docker_tag }}
          tag_latest: ${{ inputs.tag_latest }}
          push: ${{ inputs.push }}
          load: ${{ inputs.load }}
          app_version: ${{ steps.app_version.outputs.version }}
          additional_docker_build_args: ${{ inputs.additional_docker_build_args }}

      - uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/build_multiplatform_docker@v2 # WORKFLOW_VERSION
        if: ${{ ( inputs.docker_registry  == 'quay.io' ) && ( inputs.docker_multiplatform )}}
        with:
          repository_name: ${{ github.event.repository.name }}
          docker_registry: ${{ inputs.docker_registry }}
          registry_org: ${{ inputs.registry_org }}
          additional_docker_tag: ${{ inputs.additional_docker_tag }}
          tag_latest: ${{ inputs.tag_latest }}
          push: ${{ inputs.push }}
          load: ${{ inputs.load }}
          app_version: ${{ steps.app_version.outputs.version }}
          additional_docker_build_args: ${{ inputs.additional_docker_build_args }}
          HMPPS_QUAYIO_USER: ${{ secrets.HMPPS_QUAYIO_USER }}
          HMPPS_QUAYIO_TOKEN: ${{ secrets.HMPPS_QUAYIO_TOKEN}}
