name: Run gradle checks with a localstack and postgres instance
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '25'
      java-options:
        description: Any JAVA_OPTS that need to be set.  Not normally required when using github actions
        type: string
        default: ''
        required: false
      postgres-tag:
        type: string
        required: true
      postgres-password:
        type: string
        default: 'dev'
        required: false
      postgres-username:
        type: string
        default: 'root'
        required: true
      postgres-db:
        type: string
        default: 'postgres'
        required: false
      gradle-command:
        description: The gradle command to execute
        type: string
        default: './gradlew check'
        required: false
      localstack-services:
        type: string
        default: 'sqs,sns'
        required: false
      localstack-tag:
        type: string
        default: 'latest'
        required: false
      artifact-name:
        description: Unique name (across the pipeline) for the uploaded artifact
        type: string
        default: 'test-results'
        required: false
      build-artifact-name:
        description: Unique name (across the pipeline) for the uploaded build artifact
        type: string
        default: 'build-results'
        required: false
      build-dir:
        description: Path to find the artifacts e.g. necessary for multi-project gradle builds.
        type: string
        default: 'build'
        required: false
      upload-test-artifacts:
        description: Whether to upload test artifacts and generate test report
        type: boolean
        default: true
        required: false
      upload-build-artifacts:
        description: Whether to upload the uber jar and other required artifacts to build a docker image
        type: boolean
        default: false
        required: false
permissions:
  contents: read
jobs:
  gradle-localstack-postgres-verify:
    name: Verify the gradle app with localstack and postgres running
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:${{ inputs.postgres-tag }}
        env:
          POSTGRES_USER: ${{ inputs.postgres-username }}
          POSTGRES_PASSWORD: ${{ inputs.postgres-password }}
          POSTGRES_DB: ${{ inputs.postgres-db}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      localstack:
        image: localstack/localstack:${{ inputs.localstack-tag }}
        env:
          ES_PORT_EXTERNAL: 4571
          DOCKER_HOST: 'unix:///var/run/docker.sock'
          AWS_EXECUTION_ENV: True
          PERSISTENCE: 1
          SERVICES: "${{ inputs.localstack-services }}"
        options: >-
          --name localstack
          --health-cmd "curl -sS 127.0.0.1:4566 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 4566:4566
          - 4571:4571
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Set up os01 domain in localstack
        shell: bash
        run: |
          ./localstack/setup-opensearch.sh
          curl -4 --connect-timeout 30 --retry-connrefused --retry 20 --retry-delay 5 http://os01.eu-west-2.opensearch.localhost.localstack.cloud:4566
      - name: Run checks with gradle
        shell: bash
        run: |
          export JAVA_OPTS="${{ inputs.java-options }}"
          ${{ inputs.gradle-command }}
      - name: Upload the test artifacts
        if: ${{ inputs.upload-test-artifacts && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: |
            ${{ inputs.build-dir }}/test-results
            ${{ inputs.build-dir }}/reports/tests
      - name: Upload the build artifacts
        if: ${{ inputs.upload-build-artifacts && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.build-artifact-name }}
          path: |
            ${{ inputs.build-dir }}/libs
          retention-days: 1
      - name: publish test report
        if: ${{ inputs.upload-test-artifacts && !cancelled() && github.event.repository.visibility == 'public' }}
        uses: dorny/test-reporter@v2
        with:
          artifact: ${{ inputs.artifact-name }}
          name: Test Report
          path: 'test-results/**/*.xml'
          reporter: java-junit
          fail-on-empty: false
          fail-on-error: false
          list-suites: 'failed'
          list-tests: 'failed'
