name: Security veracode policy scan
on:
  workflow_dispatch:
  schedule:
    - cron: "48 4 * * 1" # Every Monday at 04:48 UTC
jobs:
  create-artifact-search:
    permissions:
      contents: read
      actions: read
    name: Build the search artifact for veracode to scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/gradle_verify.yml@v2 # WORKFLOW_VERSION
    with:
      gradle-command: 'BUILD_NUMBER=veracode ./gradlew :hmpps-prisoner-search:assemble'
      build-dir: 'hmpps-prisoner-search/build'
      upload-build-artifacts: true
      build-artifact-name: 'build-search'
      upload-test-artifacts: false
  create-artifact-indexer:
    permissions:
      contents: read
      actions: read
    name: Build the indexer artifact for veracode to scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/gradle_verify.yml@v2 # WORKFLOW_VERSION
    with:
      gradle-command: 'BUILD_NUMBER=veracode ./gradlew :hmpps-prisoner-search-indexer:assemble'
      build-dir: 'hmpps-prisoner-search-indexer/build'
      upload-build-artifacts: true
      build-artifact-name: 'build-indexer'
      upload-test-artifacts: false
  security-veracode-policy-check-search:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security veracode policy scan for search
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_policy_scan.yml@v2 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      veracode_package_artifact_name: 'build-search'
      veracode_artifact_name: 'hmpps-prisoner-search-veracode.jar'
    secrets: inherit
    needs: create-artifact-search
  security-veracode-policy-check-indexer:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security veracode policy scan for indexer
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_policy_scan.yml@v2 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      veracode_package_artifact_name: 'build-indexer'
      veracode_artifact_name: 'hmpps-prisoner-search-indexer-veracode.jar'
      application_name: 'hmpps-prisoner-search-indexer'
    secrets: inherit
    needs: create-artifact-indexer
  create-artifact:
    permissions:
      contents: read
      actions: read
