name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "53 4 * * MON-FRI" # Every weekday at 04:53 UTC
jobs:
  security-kotlin-trivy-check-search:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Search security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@v2 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      subproject: hmpps-prisoner-search
    secrets: inherit
  security-kotlin-trivy-check-indexer:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Indexer security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@v2 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      subproject: hmpps-prisoner-search-indexer
    secrets: inherit
