name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "53 4 * * MON-FRI" # Every weekday at 04:53 UTC
jobs:
  create-artifact-search:
    permissions:
      contents: read
      actions: read
    name: Build the search artifact for veracode to scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/gradle_verify.yml@v2 # WORKFLOW_VERSION
    with:
      gradle-command: 'BUILD_NUMBER=veracode ./gradlew :hmpps-prisoner-search:assemble'
      build-dir: 'hmpps-prisoner-search/build'
      upload-build-artifacts: true
      build-artifact-name: 'build-search'
      upload-test-artifacts: false
      java-version: "25"
  create-artifact-indexer:
    permissions:
      contents: read
      actions: read
    name: Build the indexer artifact for veracode to scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/gradle_verify.yml@v2 # WORKFLOW_VERSION
    with:
      gradle-command: 'BUILD_NUMBER=veracode ./gradlew :hmpps-prisoner-search-indexer:assemble'
      build-dir: 'hmpps-prisoner-search-indexer/build'
      upload-build-artifacts: true
      build-artifact-name: 'build-indexer'
      upload-test-artifacts: false
      java-version: "25"
  security-veracode-pipeline-scan-search:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security veracode pipeline scan for search
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@v2 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      veracode_package_artifact_name: 'build-search'
      veracode_artifact_name: 'hmpps-prisoner-search-veracode.jar'
    secrets: inherit
    needs: create-artifact-search
  security-veracode-pipeline-scan-indexer:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security veracode pipeline scan for indexer
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@v2 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      veracode_package_artifact_name: 'build-indexer'
      veracode_artifact_name: 'hmpps-prisoner-search-indexer-veracode.jar'
    secrets: inherit
    needs: create-artifact-indexer
