name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "20 5 * * MON-FRI" # Every weekday at 05:20 UTC
jobs:
  security-kotlin-trivy-check-search:
    name: Search security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@v0.6 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      subproject: hmpps-prisoner-search
    secrets: inherit
  security-kotlin-trivy-check-indexer:
    name: Indexer security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@v0.6 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      subproject: hmpps-prisoner-search-indexer
    secrets: inherit
