name: Gradle OWASP security check

on:
  schedule:
    - cron: "0 6 * * MON-FRI" # Every weekday at 06:00 UTC

permissions:
  contents: read

jobs:
  security-gradle-owasp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Run gradle OWASP
      run: ./gradlew dependencyCheckAnalyze
    - uses: actions/upload-artifact@v3
      with:
        name: dependency-check-reports
        path: |
          */build/reports/dependency-check-report.html
