name: Security trivy dependency check

on:
  workflow_call:
    inputs:
      subproject:
        required: false
        type: string

permissions:
  contents: read

jobs:
  security-trivy-check:
    name: Security trivy dependency check
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      parent_directory: ${{ inputs.subproject == '' && '.' || inputs.subproject }}
    steps:
    - uses: actions/checkout@v4
    - name: Trivy Image Vulnerability Scanner
      id: trivy
      uses: aquasecurity/trivy-action@b5f4977b78f81fa3d48865ff0efcc6e279210235 # v0.50.2
      with:
        image-ref: 'quay.io/hmpps/${{ inputs.subproject }}:latest'
        severity: 'HIGH,CRITICAL'
        ignore-unfixed: true
        skip-files: /app/agent.jar
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: 1
    - uses: github/codeql-action/upload-sarif@v3
      if: success() || steps.trivy.conclusion == 'failure'
      with:
        sarif_file: 'trivy-results.sarif'
        category: trivy-dependency-check
    - uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
      if: failure()
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":no_entry: Failed GitHub Action:"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Job:*\n${{ github.job }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repo:*\n${{ github.repository }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
