name: Security OWASP dependency check

on:
  workflow_call:
    inputs:
      subproject:
        required: false
        type: string
      slack_webhook_url:
        description: Slack webhook
        required: true

permissions:
  contents: read

jobs:
  security-owasp-check:
    name: Security OWASP dependency check
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      parent_directory: ${{ inputs.subproject == '' && '.' || inputs.subproject }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Run gradle OWASP
      id: owasp
      run: ./gradlew ${{ inputs.subproject }}:dependencyCheckAnalyze
    - uses: github/codeql-action/upload-sarif@v3
      if: success() || steps.owasp.conclusion == 'failure'
      with:
        sarif_file: ${{ env.parent_directory }}/build/reports/dependency-check-report.sarif
        category: gradle-owasp-dependency-check
    - uses: actions/upload-artifact@v3
      if: success() || steps.owasp.conclusion == 'failure'
      with:
        name: gradle-owasp-dependency-check-${{ inputs.subproject }}
        path: ${{ env.parent_directory }}/build/reports/dependency-check-report.html
    - uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
      if: failure()
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":no_entry: Failed GitHub Action:"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Job:*\n${{ github.job }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repo:*\n${{ github.repository }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
