name: Parent security OWASP dependency check

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * MON-FRI" # Every weekday at 05:30 UTC

jobs:
  security-owasp-search-check:
    name: Search security OWASP dependency check
    uses: ./.github/workflows/security_owasp.yml
    with:
      subproject: hmpps-prisoner-search
  security-owasp-indexer-check:
    name: Indexer security OWASP dependency check
    uses: ./.github/workflows/security_owasp.yml
    with:
      subproject: hmpps-prisoner-search-indexer
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
