name: Security OWASP dependency check

on:
  workflow_call:
    inputs:
      subproject:
        required: false
        type: string

permissions:
  contents: read

jobs:
  security-owasp-check:
    name: Security OWASP dependency check
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
    - name: Run gradle OWASP
      id: owasp
      run: ./gradlew ${{ inputs.subproject }}:dependencyCheckAnalyze
    - uses: github/codeql-action/upload-sarif@v2
      if: success() || steps.owasp.conclusion == 'failure'
      with:
        sarif_file: ${{ env.parent_directory }}/build/reports/dependency-check-report.sarif
        category: gradle-owasp-dependency-check
      env:
        parent_directory: ${{ inputs.subproject == '' && '.' || inputs.subproject }}
    - uses: actions/upload-artifact@v3
      with:
        name: gradle-owasp-dependency-check
        path: ${{ env.parent_directory }}/build/reports/dependency-check-report.html
