name: Runs the smoke tests in a hmpps github actions runner
on:
  workflow_call:
    secrets:
      GRADLE_CACHE_ENCRYPTION_KEY:
        required: false
    inputs:
      java-version:
        type: string
        required: false
        default: '25'
      java-options:
        type: string
        default: ''
        required: false
      gradle-command:
        type: string
        default: "./gradlew testSmoke -Dtestlogger.showStandardStreams=true"
        required: false
      build-dir:
        type: string
        default: 'build'
        required: false
permissions:
  contents: read
jobs:
  smoke-test:
    name: Runs the smoke tests using gradle
    runs-on: [self-hosted, hmpps-github-actions-runner]
    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
      - name: Run smoke tests with gradle
        shell: bash
        run: |
          export JAVA_OPTS="${{ inputs.java-options }}"
          ${{ inputs.gradle-command }}
        env:
          SMOKETEST_CLIENT_CLIENT_ID: ${{ secrets.SMOKETEST_CLIENT_CLIENT_ID }}
          SMOKETEST_CLIENT_CLIENT_SECRET: ${{ secrets.SMOKETEST_CLIENT_CLIENT_SECRET }}
          SMOKETEST_ENDPOINT_URL: ${{ vars.SMOKETEST_ENDPOINT_URL }}
          SMOKETEST_HMPPS_AUTH_ENDPOINT_URL: ${{ vars.SMOKETEST_HMPPS_AUTH_ENDPOINT_URL }}
      - name: Upload the artifacts
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: upload smoke test results
          path: |
            ${{ inputs.build-dir }}/test-results
            ${{ inputs.build-dir }}/reports/tests
